// https://android.googlesource.com/platform/external/bluetooth/bluedroid/+/master/stack/include/hcidefs.h

/**
 * Common definitions
 *
 * @author   Jelle De Loecker <jelle@develry.be>
 * @since    0.1.0
 * @version  0.1.0
 */
var self = this = {
/*
// Group occupies high 6 bits of the HCI command rest is opcode itself
#define HCI_OGF(p)  (UINT8)((0xFC00 & (p)) >> 10)
#define HCI_OCF(p)  ( 0x3FF & (p))

// Following opcode is used only in command complete event for flow control
#define HCI_COMMAND_NONE                0x0000

#define HCI_VENDOR_CMDS_FIRST           0x0001
#define HCI_VENDOR_CMDS_LAST            0xFFFF
#define HCI_VSC_MULTI_AV_HANDLE         0x0AAA
#define HCI_VSC_BURST_MODE_HANDLE       0x0BBB
*/
};

/**
 * Protocol version information
 *
 * @author   Jelle De Loecker <jelle@develry.be>
 * @since    0.1.0
 * @version  0.1.0
 */
this.PROTO = {
	VERSION      : 0x01,    // BT 1.1
	VERSION_1_2  : 0x02,    // BT 1.2
	VERSION_2_0  : 0x03,    // BT 2.0
	VERSION_2_1  : 0x04,    // BT 2.1
	VERSION_3_0  : 0x05,    // BT 3.0
	REVISION     : 0x000C   // Current implementation version ?
};

/**
 * Definitions for HCI groups
 *
 * @author   Jelle De Loecker <jelle@develry.be>
 * @since    0.1.0
 * @version  0.1.0
 */
this.GRP = {
	LINK_CONTROL_CMDS       : 0x01 << 10, // 0x0400
	LINK_POLICY_CMDS        : 0x02 << 10, // 0x0800
	HOST_CONT_BASEBAND_CMDS : 0x03 << 10, // 0x0C00
	INFORMATIONAL_PARAMS    : 0x04 << 10, // 0x1000
	STATUS_PARAMS           : 0x05 << 10, // 0x1400
	TESTING_CMDS            : 0x06 << 10, // 0x1800
	BLE_CMDS                : 0x08 << 10, // 0x2000 (BLE)
	VENDOR_SPECIFIC         : 0x3F << 10, // 0xFC00
	LINK                    : {},
	HOST                    : {}
};

/**
 * Definitions for Link control commands
 *
 * @author   Jelle De Loecker <jelle@develry.be>
 * @since    0.1.0
 * @version  0.1.0
 */
this.GRP.LINK.CONTROL = {
	INQUIRY                    : 0x0001 | self.GRP.LINK_CONTROL_CMDS,
	INQUIRY_CANCEL             : 0x0002 | self.GRP.LINK_CONTROL_CMDS,
	PERIODIC_INQUIRY_MODE      : 0x0003 | self.GRP.LINK_CONTROL_CMDS,
	EXIT_PERIODIC_INQUIRY_MODE : 0x0004 | self.GRP.LINK_CONTROL_CMDS,
	CREATE_CONNECTION          : 0x0005 | self.GRP.LINK_CONTROL_CMDS,
	DISCONNECT                 : 0x0006 | self.GRP.LINK_CONTROL_CMDS,
	ADD_SCO_CONNECTION         : 0x0007 | self.GRP.LINK_CONTROL_CMDS,
	CREATE_CONNECTION_CANCEL   : 0x0008 | self.GRP.LINK_CONTROL_CMDS,
	ACCEPT_CONNECTION_REQUEST  : 0x0009 | self.GRP.LINK_CONTROL_CMDS,
	REJECT_CONNECTION_REQUEST  : 0x000A | self.GRP.LINK_CONTROL_CMDS,
	LINK_KEY_REQUEST_REPLY     : 0x000B | self.GRP.LINK_CONTROL_CMDS,
	LINK_KEY_REQUEST_NEG_REPLY : 0x000C | self.GRP.LINK_CONTROL_CMDS,
	PIN_CODE_REQUEST_REPLY     : 0x000D | self.GRP.LINK_CONTROL_CMDS,
	PIN_CODE_REQUEST_NEG_REPLY : 0x000E | self.GRP.LINK_CONTROL_CMDS,
	CHANGE_CONN_PACKET_TYPE    : 0x000F | self.GRP.LINK_CONTROL_CMDS,
	AUTHENTICATION_REQUESTED   : 0x0011 | self.GRP.LINK_CONTROL_CMDS,
	SET_CONN_ENCRYPTION        : 0x0013 | self.GRP.LINK_CONTROL_CMDS,
	CHANGE_CONN_LINK_KEY       : 0x0015 | self.GRP.LINK_CONTROL_CMDS,
	MASTER_LINK_KEY            : 0x0017 | self.GRP.LINK_CONTROL_CMDS,
	RMT_NAME_REQUEST           : 0x0019 | self.GRP.LINK_CONTROL_CMDS,
	RMT_NAME_REQUEST_CANCEL    : 0x001A | self.GRP.LINK_CONTROL_CMDS,
	READ_RMT_FEATURES          : 0x001B | self.GRP.LINK_CONTROL_CMDS,
	READ_RMT_EXT_FEATURES      : 0x001C | self.GRP.LINK_CONTROL_CMDS,
	READ_RMT_VERSION_INFO      : 0x001D | self.GRP.LINK_CONTROL_CMDS,
	READ_RMT_CLOCK_OFFSET      : 0x001F | self.GRP.LINK_CONTROL_CMDS,
	READ_LMP_HANDLE            : 0x0020 | self.GRP.LINK_CONTROL_CMDS,
	SETUP_ESCO_CONNECTION      : 0x0028 | self.GRP.LINK_CONTROL_CMDS,
	ACCEPT_ESCO_CONNECTION     : 0x0029 | self.GRP.LINK_CONTROL_CMDS,
	REJECT_ESCO_CONNECTION     : 0x002A | self.GRP.LINK_CONTROL_CMDS,
	IO_CAPABILITY_RESPONSE     : 0x002B | self.GRP.LINK_CONTROL_CMDS,
	USER_CONF_REQUEST_REPLY    : 0x002C | self.GRP.LINK_CONTROL_CMDS,
	USER_CONF_VALUE_NEG_REPLY  : 0x002D | self.GRP.LINK_CONTROL_CMDS,
	USER_PASSKEY_REQ_REPLY     : 0x002E | self.GRP.LINK_CONTROL_CMDS,
	USER_PASSKEY_REQ_NEG_REPLY : 0x002F | self.GRP.LINK_CONTROL_CMDS,
	REM_OOB_DATA_REQ_REPLY     : 0x0030 | self.GRP.LINK_CONTROL_CMDS,
	REM_OOB_DATA_REQ_NEG_REPLY : 0x0033 | self.GRP.LINK_CONTROL_CMDS,
	IO_CAP_REQ_NEG_REPLY       : 0x0034 | self.GRP.LINK_CONTROL_CMDS,

	// AMP HCI
	CREATE_PHYSICAL_LINK       : 0x0035 | self.GRP.LINK_CONTROL_CMDS,
	ACCEPT_PHYSICAL_LINK       : 0x0036 | self.GRP.LINK_CONTROL_CMDS,
	DISCONNECT_PHYSICAL_LINK   : 0x0037 | self.GRP.LINK_CONTROL_CMDS,
	CREATE_LOGICAL_LINK        : 0x0038 | self.GRP.LINK_CONTROL_CMDS,
	ACCEPT_LOGICAL_LINK        : 0x0039 | self.GRP.LINK_CONTROL_CMDS,
	DISCONNECT_LOGICAL_LINK    : 0x003A | self.GRP.LINK_CONTROL_CMDS,
	LOGICAL_LINK_CANCEL        : 0x003B | self.GRP.LINK_CONTROL_CMDS,
	FLOW_SPEC_MODIFY           : 0x003C | self.GRP.LINK_CONTROL_CMDS,
	ENH_SETUP_ESCO_CONNECTION  : 0x003D | self.GRP.LINK_CONTROL_CMDS,
	ENH_ACCEPT_ESCO_CONNECTION : 0x003E | self.GRP.LINK_CONTROL_CMDS,

	// ConnectionLess Broadcast
	TRUNCATED_PAGE             : 0x003F | self.GRP.LINK_CONTROL_CMDS,
	TRUNCATED_PAGE_CANCEL      : 0x0040 | self.GRP.LINK_CONTROL_CMDS,
	SET_CLB                    : 0x0041 | self.GRP.LINK_CONTROL_CMDS,
	RECEIVE_CLB                : 0x0042 | self.GRP.LINK_CONTROL_CMDS,
	START_SYNC_TRAIN           : 0x0043 | self.GRP.LINK_CONTROL_CMDS,
	RECEIVE_SYNC_TRAIN         : 0x0044 | self.GRP.LINK_CONTROL_CMDS
};

/**
 * Definitions for Link policy commands
 *
 * @author   Jelle De Loecker <jelle@develry.be>
 * @since    0.1.0
 * @version  0.1.0
 */
this.GRP.LINK.POLICY = {
	HOLD_MODE                  : 0x0001 | self.GRP.LINK_POLICY_CMDS,
	SNIFF_MODE                 : 0x0003 | self.GRP.LINK_POLICY_CMDS,
	EXIT_SNIFF_MODE            : 0x0004 | self.GRP.LINK_POLICY_CMDS,
	PARK_MODE                  : 0x0005 | self.GRP.LINK_POLICY_CMDS,
	EXIT_PARK_MODE             : 0x0006 | self.GRP.LINK_POLICY_CMDS,
	QOS_SETUP                  : 0x0007 | self.GRP.LINK_POLICY_CMDS,
	ROLE_DISCOVERY             : 0x0009 | self.GRP.LINK_POLICY_CMDS,
	SWITCH_ROLE                : 0x000B | self.GRP.LINK_POLICY_CMDS,
	READ_POLICY_SETTINGS       : 0x000C | self.GRP.LINK_POLICY_CMDS,
	WRITE_POLICY_SETTINGS      : 0x000D | self.GRP.LINK_POLICY_CMDS,
	READ_DEF_POLICY_SETTINGS   : 0x000E | self.GRP.LINK_POLICY_CMDS,
	WRITE_DEF_POLICY_SETTINGS  : 0x000F | self.GRP.LINK_POLICY_CMDS,
	FLOW_SPECIFICATION         : 0x0010 | self.GRP.LINK_POLICY_CMDS,
	SNIFF_SUB_RATE             : 0x0011 | self.GRP.LINK_POLICY_CMDS
};

/**
 * Definitions for Host cont baseband commands
 *
 * @author   Jelle De Loecker <jelle@develry.be>
 * @since    0.1.0
 * @version  0.1.0
 */
this.GRP.HOST.BASE = {
	SET_EVENT_MASK              : 0x0001 | self.GRP.HOST_CONT_BASEBAND_CMDS,
	RESET                       : 0x0003 | self.GRP.HOST_CONT_BASEBAND_CMDS,
	SET_EVENT_FILTER            : 0x0005 | self.GRP.HOST_CONT_BASEBAND_CMDS,
	FLUSH                       : 0x0008 | self.GRP.HOST_CONT_BASEBAND_CMDS,
	READ_PIN_TYPE               : 0x0009 | self.GRP.HOST_CONT_BASEBAND_CMDS,
	WRITE_PIN_TYPE              : 0x000A | self.GRP.HOST_CONT_BASEBAND_CMDS,
	CREATE_NEW_UNIT_KEY         : 0x000B | self.GRP.HOST_CONT_BASEBAND_CMDS,
	GET_MWS_TRANS_LAYER_CFG     : 0x000C | self.GRP.HOST_CONT_BASEBAND_CMDS,
	READ_STORED_LINK_KEY        : 0x000D | self.GRP.HOST_CONT_BASEBAND_CMDS,
	WRITE_STORED_LINK_KEY       : 0x0011 | self.GRP.HOST_CONT_BASEBAND_CMDS,
	DELETE_STORED_LINK_KEY      : 0x0012 | self.GRP.HOST_CONT_BASEBAND_CMDS,
	CHANGE_LOCAL_NAME           : 0x0013 | self.GRP.HOST_CONT_BASEBAND_CMDS,
	READ_LOCAL_NAME             : 0x0014 | self.GRP.HOST_CONT_BASEBAND_CMDS,
	READ_CONN_ACCEPT_TOUT       : 0x0015 | self.GRP.HOST_CONT_BASEBAND_CMDS,
	WRITE_CONN_ACCEPT_TOUT      : 0x0016 | self.GRP.HOST_CONT_BASEBAND_CMDS,
	READ_PAGE_TOUT              : 0x0017 | self.GRP.HOST_CONT_BASEBAND_CMDS,
	WRITE_PAGE_TOUT             : 0x0018 | self.GRP.HOST_CONT_BASEBAND_CMDS,
	READ_SCAN_ENABLE            : 0x0019 | self.GRP.HOST_CONT_BASEBAND_CMDS,
	WRITE_SCAN_ENABLE           : 0x001A | self.GRP.HOST_CONT_BASEBAND_CMDS,
	READ_PAGESCAN_CFG           : 0x001B | self.GRP.HOST_CONT_BASEBAND_CMDS,
	WRITE_PAGESCAN_CFG          : 0x001C | self.GRP.HOST_CONT_BASEBAND_CMDS,
	READ_INQUIRYSCAN_CFG        : 0x001D | self.GRP.HOST_CONT_BASEBAND_CMDS,
	WRITE_INQUIRYSCAN_CFG       : 0x001E | self.GRP.HOST_CONT_BASEBAND_CMDS,
	READ_AUTHENTICATION_ENABLE  : 0x001F | self.GRP.HOST_CONT_BASEBAND_CMDS,
	WRITE_AUTHENTICATION_ENABLE : 0x0020 | self.GRP.HOST_CONT_BASEBAND_CMDS,
	READ_ENCRYPTION_MODE        : 0x0021 | self.GRP.HOST_CONT_BASEBAND_CMDS,
	WRITE_ENCRYPTION_MODE       : 0x0022 | self.GRP.HOST_CONT_BASEBAND_CMDS,
	READ_CLASS_OF_DEVICE        : 0x0023 | self.GRP.HOST_CONT_BASEBAND_CMDS,
	WRITE_CLASS_OF_DEVICE       : 0x0024 | self.GRP.HOST_CONT_BASEBAND_CMDS,
	READ_VOICE_SETTINGS         : 0x0025 | self.GRP.HOST_CONT_BASEBAND_CMDS,
	WRITE_VOICE_SETTINGS        : 0x0026 | self.GRP.HOST_CONT_BASEBAND_CMDS,
	READ_AUTO_FLUSH_TOUT        : 0x0027 | self.GRP.HOST_CONT_BASEBAND_CMDS,
	WRITE_AUTO_FLUSH_TOUT       : 0x0028 | self.GRP.HOST_CONT_BASEBAND_CMDS,
	READ_NUM_BCAST_REXMITS      : 0x0029 | self.GRP.HOST_CONT_BASEBAND_CMDS,
	WRITE_NUM_BCAST_REXMITS     : 0x002A | self.GRP.HOST_CONT_BASEBAND_CMDS,
	READ_HOLD_MODE_ACTIVITY     : 0x002B | self.GRP.HOST_CONT_BASEBAND_CMDS,
	WRITE_HOLD_MODE_ACTIVITY    : 0x002C | self.GRP.HOST_CONT_BASEBAND_CMDS,
	READ_TRANSMIT_POWER_LEVEL   : 0x002D | self.GRP.HOST_CONT_BASEBAND_CMDS,
	READ_SCO_FLOW_CTRL_ENABLE   : 0x002E | self.GRP.HOST_CONT_BASEBAND_CMDS,
	WRITE_SCO_FLOW_CTRL_ENABLE  : 0x002F | self.GRP.HOST_CONT_BASEBAND_CMDS,
	SET_HC_TO_HOST_FLOW_CTRL    : 0x0031 | self.GRP.HOST_CONT_BASEBAND_CMDS,
	HOST_BUFFER_SIZE            : 0x0033 | self.GRP.HOST_CONT_BASEBAND_CMDS,
	HOST_NUM_PACKETS_DONE       : 0x0035 | self.GRP.HOST_CONT_BASEBAND_CMDS,
	READ_LINK_SUPER_TOUT        : 0x0036 | self.GRP.HOST_CONT_BASEBAND_CMDS,
	WRITE_LINK_SUPER_TOUT       : 0x0037 | self.GRP.HOST_CONT_BASEBAND_CMDS,
	READ_NUM_SUPPORTED_IAC      : 0x0038 | self.GRP.HOST_CONT_BASEBAND_CMDS,
	READ_CURRENT_IAC_LAP        : 0x0039 | self.GRP.HOST_CONT_BASEBAND_CMDS,
	WRITE_CURRENT_IAC_LAP       : 0x003A | self.GRP.HOST_CONT_BASEBAND_CMDS,
	READ_PAGESCAN_PERIOD_MODE   : 0x003B | self.GRP.HOST_CONT_BASEBAND_CMDS,
	WRITE_PAGESCAN_PERIOD_MODE  : 0x003C | self.GRP.HOST_CONT_BASEBAND_CMDS,
	READ_PAGESCAN_MODE          : 0x003D | self.GRP.HOST_CONT_BASEBAND_CMDS,
	WRITE_PAGESCAN_MODE         : 0x003E | self.GRP.HOST_CONT_BASEBAND_CMDS,
	SET_AFH_CHANNELS            : 0x003F | self.GRP.HOST_CONT_BASEBAND_CMDS,
	READ_INQSCAN_TYPE           : 0x0042 | self.GRP.HOST_CONT_BASEBAND_CMDS,
	WRITE_INQSCAN_TYPE          : 0x0043 | self.GRP.HOST_CONT_BASEBAND_CMDS,
	READ_INQUIRY_MODE           : 0x0044 | self.GRP.HOST_CONT_BASEBAND_CMDS,
	WRITE_INQUIRY_MODE          : 0x0045 | self.GRP.HOST_CONT_BASEBAND_CMDS,
	READ_PAGESCAN_TYPE          : 0x0046 | self.GRP.HOST_CONT_BASEBAND_CMDS,
	WRITE_PAGESCAN_TYPE         : 0x0047 | self.GRP.HOST_CONT_BASEBAND_CMDS,
	READ_AFH_ASSESSMENT_MODE    : 0x0048 | self.GRP.HOST_CONT_BASEBAND_CMDS,
	WRITE_AFH_ASSESSMENT_MODE   : 0x0049 | self.GRP.HOST_CONT_BASEBAND_CMDS,
	READ_EXT_INQ_RESPONSE       : 0x0051 | self.GRP.HOST_CONT_BASEBAND_CMDS,
	WRITE_EXT_INQ_RESPONSE      : 0x0052 | self.GRP.HOST_CONT_BASEBAND_CMDS,
	REFRESH_ENCRYPTION_KEY      : 0x0053 | self.GRP.HOST_CONT_BASEBAND_CMDS,
	READ_SIMPLE_PAIRING_MODE    : 0x0055 | self.GRP.HOST_CONT_BASEBAND_CMDS,
	WRITE_SIMPLE_PAIRING_MODE   : 0x0056 | self.GRP.HOST_CONT_BASEBAND_CMDS,
	READ_LOCAL_OOB_DATA         : 0x0057 | self.GRP.HOST_CONT_BASEBAND_CMDS,
	READ_INQ_TX_POWER_LEVEL     : 0x0058 | self.GRP.HOST_CONT_BASEBAND_CMDS,
	WRITE_INQ_TX_POWER_LEVEL    : 0x0059 | self.GRP.HOST_CONT_BASEBAND_CMDS,
	READ_ERRONEOUS_DATA_RPT     : 0x005A | self.GRP.HOST_CONT_BASEBAND_CMDS,
	WRITE_ERRONEOUS_DATA_RPT    : 0x005B | self.GRP.HOST_CONT_BASEBAND_CMDS,
	ENHANCED_FLUSH              : 0x005F | self.GRP.HOST_CONT_BASEBAND_CMDS,
	SEND_KEYPRESS_NOTIF         : 0x0060 | self.GRP.HOST_CONT_BASEBAND_CMDS,

	// AMP HCI
	READ_LOGICAL_LINK_ACCEPT_TIMEOUT  : 0x0061 | self.GRP.HOST_CONT_BASEBAND_CMDS,
	WRITE_LOGICAL_LINK_ACCEPT_TIMEOUT : 0x0062 | self.GRP.HOST_CONT_BASEBAND_CMDS,
	SET_EVENT_MASK_PAGE_2             : 0x0063 | self.GRP.HOST_CONT_BASEBAND_CMDS,
	READ_LOCATION_DATA                : 0x0064 | self.GRP.HOST_CONT_BASEBAND_CMDS,
	WRITE_LOCATION_DATA               : 0x0065 | self.GRP.HOST_CONT_BASEBAND_CMDS,
	READ_FLOW_CONTROL_MODE            : 0x0066 | self.GRP.HOST_CONT_BASEBAND_CMDS,
	WRITE_FLOW_CONTROL_MODE           : 0x0067 | self.GRP.HOST_CONT_BASEBAND_CMDS,
	READ_BE_FLUSH_TOUT                : 0x0069 | self.GRP.HOST_CONT_BASEBAND_CMDS,
	WRITE_BE_FLUSH_TOUT               : 0x006A | self.GRP.HOST_CONT_BASEBAND_CMDS,
	SHORT_RANGE_MODE                  : 0x006B | self.GRP.HOST_CONT_BASEBAND_CMDS, // 802.11 only
	READ_LE_HOST_SUPPORTED            : 0x006C | self.GRP.HOST_CONT_BASEBAND_CMDS,
	WRITE_LE_HOST_SUPPORTED           : 0x006D | self.GRP.HOST_CONT_BASEBAND_CMDS,

	// MWS coexistence
	SET_MWS_CHANNEL_PARAMETERS        : 0x006E | self.GRP.HOST_CONT_BASEBAND_CMDS,
	SET_EXTERNAL_FRAME_CONFIGURATION  : 0x006F | self.GRP.HOST_CONT_BASEBAND_CMDS,
	SET_MWS_SIGNALING                 : 0x0070 | self.GRP.HOST_CONT_BASEBAND_CMDS,
	SET_MWS_TRANSPORT_LAYER           : 0x0071 | self.GRP.HOST_CONT_BASEBAND_CMDS,
	SET_MWS_SCAN_FREQUENCY_TABLE      : 0x0072 | self.GRP.HOST_CONT_BASEBAND_CMDS,
	SET_MWS_PATTERN_CONFIGURATION     : 0x0073 | self.GRP.HOST_CONT_BASEBAND_CMDS,

	// ConnectionLess Broadcast
	SET_RESERVED_LT_ADDR              : 0x0074 | self.GRP.HOST_CONT_BASEBAND_CMDS,
	DELETE_RESERVED_LT_ADDR           : 0x0075 | self.GRP.HOST_CONT_BASEBAND_CMDS,
	WRITE_CLB_DATA                    : 0x0076 | self.GRP.HOST_CONT_BASEBAND_CMDS,
	READ_SYNC_TRAIN_PARAM             : 0x0077 | self.GRP.HOST_CONT_BASEBAND_CMDS,
	WRITE_SYNC_TRAIN_PARAM            : 0x0078 | self.GRP.HOST_CONT_BASEBAND_CMDS
};

/**
 * Definitions for informational parameters
 *
 * @author   Jelle De Loecker <jelle@develry.be>
 * @since    0.1.0
 * @version  0.1.0
 */
this.GRP.INFO = {
	READ_LOCAL_VERSION_INFO     : 0x0001 | self.GRP.INFORMATIONAL_PARAMS,
	READ_LOCAL_SUPPORTED_CMDS   : 0x0002 | self.GRP.INFORMATIONAL_PARAMS,
	READ_LOCAL_FEATURES         : 0x0003 | self.GRP.INFORMATIONAL_PARAMS,
	READ_LOCAL_EXT_FEATURES     : 0x0004 | self.GRP.INFORMATIONAL_PARAMS,
	READ_BUFFER_SIZE            : 0x0005 | self.GRP.INFORMATIONAL_PARAMS,
	READ_COUNTRY_CODE           : 0x0007 | self.GRP.INFORMATIONAL_PARAMS,
	READ_BD_ADDR                : 0x0009 | self.GRP.INFORMATIONAL_PARAMS,
	READ_DATA_BLOCK_SIZE        : 0x000A | self.GRP.INFORMATIONAL_PARAMS,
	READ_LOCAL_SUPPORTED_CODECS : 0x000B | self.GRP.INFORMATIONAL_PARAMS
};

/**
 * Definitions for status parameters
 *
 * @author   Jelle De Loecker <jelle@develry.be>
 * @since    0.1.0
 * @version  0.1.0
 */
this.GRP.STATUS = {
	READ_FAILED_CONTACT_COUNT   : 0x0001 | self.GRP.STATUS_PARAMS,
	RESET_FAILED_CONTACT_COUNT  : 0x0002 | self.GRP.STATUS_PARAMS,
	GET_LINK_QUALITY            : 0x0003 | self.GRP.STATUS_PARAMS,
	READ_RSSI                   : 0x0005 | self.GRP.STATUS_PARAMS,
	READ_AFH_CH_MAP             : 0x0006 | self.GRP.STATUS_PARAMS,
	READ_CLOCK                  : 0x0007 | self.GRP.STATUS_PARAMS,
	READ_ENCR_KEY_SIZE          : 0x0008 | self.GRP.STATUS_PARAMS,

	// AMP HCI
	READ_LOCAL_AMP_INFO         : 0x0009 | self.GRP.STATUS_PARAMS,
	READ_LOCAL_AMP_ASSOC        : 0x000A | self.GRP.STATUS_PARAMS,
	WRITE_REMOTE_AMP_ASSOC      : 0x000B | self.GRP.STATUS_PARAMS
};

/**
 * Definitions for testing commands
 *
 * @author   Jelle De Loecker <jelle@develry.be>
 * @since    0.1.0
 * @version  0.1.0
 */
this.GRP.TEST = {
	READ_LOOPBACK_MODE          : 0x0001 | self.GRP.TESTING_CMDS,
	WRITE_LOOPBACK_MODE         : 0x0002 | self.GRP.TESTING_CMDS,
	ENABLE_DEV_UNDER_TEST_MODE  : 0x0003 | self.GRP.TESTING_CMDS,
	WRITE_SIMP_PAIR_DEBUG_MODE  : 0x0004 | self.GRP.TESTING_CMDS,

	// AMP HCI
	ENABLE_AMP_RCVR_REPORTS     : 0x0007 | self.GRP.TESTING_CMDS,
	AMP_TEST_END                : 0x0008 | self.GRP.TESTING_CMDS,
	AMP_TEST                    : 0x0009 | self.GRP.TESTING_CMDS
};

/**
 * Definitions for BLE controller setup and configuration commands
 *
 * @author   Jelle De Loecker <jelle@develry.be>
 * @since    0.1.0
 * @version  0.1.0
 */
this.BLE = {
	SET_EVENT_MASK          : 0x0001 | self.GRP.BLE_CMDS,
	READ_BUFFER_SIZE        : 0x0002 | self.GRP.BLE_CMDS,
	READ_LOCAL_SPT_FEAT     : 0x0003 | self.GRP.BLE_CMDS,
	WRITE_LOCAL_SPT_FEAT    : 0x0004 | self.GRP.BLE_CMDS,
	WRITE_RANDOM_ADDR       : 0x0005 | self.GRP.BLE_CMDS,
	WRITE_ADV_PARAMS        : 0x0006 | self.GRP.BLE_CMDS,
	READ_ADV_CHNL_TX_POWER  : 0x0007 | self.GRP.BLE_CMDS,
	WRITE_ADV_DATA          : 0x0008 | self.GRP.BLE_CMDS,
	WRITE_SCAN_RSP_DATA     : 0x0009 | self.GRP.BLE_CMDS,
	WRITE_ADV_ENABLE        : 0x000A | self.GRP.BLE_CMDS,
	WRITE_SCAN_PARAMS       : 0x000B | self.GRP.BLE_CMDS,
	WRITE_SCAN_ENABLE       : 0x000C | self.GRP.BLE_CMDS,
	CREATE_LL_CONN          : 0x000D | self.GRP.BLE_CMDS,
	CREATE_CONN_CANCEL      : 0x000E | self.GRP.BLE_CMDS,
	READ_WHITE_LIST_SIZE    : 0x000F | self.GRP.BLE_CMDS,
	CLEAR_WHITE_LIST        : 0x0010 | self.GRP.BLE_CMDS,
	ADD_WHITE_LIST          : 0x0011 | self.GRP.BLE_CMDS,
	REMOVE_WHITE_LIST       : 0x0012 | self.GRP.BLE_CMDS,
	UPD_LL_CONN_PARAMS      : 0x0013 | self.GRP.BLE_CMDS,
	SET_HOST_CHNL_CLASS     : 0x0014 | self.GRP.BLE_CMDS,
	READ_CHNL_MAP           : 0x0015 | self.GRP.BLE_CMDS,
	READ_REMOTE_FEAT        : 0x0016 | self.GRP.BLE_CMDS,
	ENCRYPT                 : 0x0017 | self.GRP.BLE_CMDS,
	RAND                    : 0x0018 | self.GRP.BLE_CMDS,
	START_ENC               : 0x0019 | self.GRP.BLE_CMDS,
	LTK_REQ_REPLY           : 0x001A | self.GRP.BLE_CMDS,
	LTK_REQ_NEG_REPLY       : 0x001B | self.GRP.BLE_CMDS,
	READ_SUPPORTED_STATES   : 0x001C | self.GRP.BLE_CMDS,
	// 0x001D, 0x001E and 0x001F are reserved

	RC_PARAM_REQ_REPLY      : 0x0020 | self.GRP.BLE_CMDS,
	RC_PARAM_REQ_NEG_REPLY  : 0x0021 | self.GRP.BLE_CMDS,

	// BLE TEST COMMANDS
	RECEIVER_TEST           : 0x001D | self.GRP.BLE_CMDS,
	TRANSMITTER_TEST        : 0x001E | self.GRP.BLE_CMDS,
	TEST_END                : 0x001F | self.GRP.BLE_CMDS,

	// Vendor specific things
	VENDOR_CAP_OCF          : 0x0153 | self.GRP.VENDOR_SPECIFIC, // LE Get Vendor Capabilities Command OCF
	MULTI_ADV_OCF           : 0x0154 | self.GRP.VENDOR_SPECIFIC, // Multi adv OCF
	BATCH_SCAN_OCF          : 0x0156 | self.GRP.VENDOR_SPECIFIC, // Batch scan OCF
	ADV_FILTER_OCF          : 0x0157 | self.GRP.VENDOR_SPECIFIC, // ADV filter OCF
	TRACK_ADV_OCF           : 0x0158 | self.GRP.VENDOR_SPECIFIC, // Tracking OCF
	ENERGY_INFO_OCF         : 0x0159 | self.GRP.VENDOR_SPECIFIC, // Energy info OCF

	// Events
	THRESHOLD_SUB_EVT       : 0x54, // Threshold event
	TRACKING_SUB_EVT        : 0x56  // Tracking event
};

/**
 * Definitions for advanced BLE features
 *
 * @author   Jelle De Loecker <jelle@develry.be>
 * @since    0.1.0
 * @version  0.1.0
 */
this.BLE.ADV = {
	SET_PARAM                    : 0x01,
	WRITE_ADV_DATA               : 0x02,
	WRITE_SCAN_RSP_DATA          : 0x03,
	SET_RANDOM_ADDR              : 0x04,
	ENB                          : 0x05,
	ST_CHG                       : 0x55  // Multi adv instance state change
};

/**
 * Definitions for BLE batch scans
 *
 * @author   Jelle De Loecker <jelle@develry.be>
 * @since    0.1.0
 * @version  0.1.0
 */
this.BLE.BATCH = {
	SCAN_ENB_DISAB_CUST_FEATURE      : 0x01,
	SCAN_SET_STORAGE_PARAM           : 0x02,
	SCAN_SET_PARAMS                  : 0x03,
	SCAN_READ_RESULTS                : 0x04,
	THRESHOLD_SUB_EVT                : 0x54, // Threshold event
	TRACKING_SUB_EVT                 : 0x56  // Tracking event
};

/**
 * Definitions for BLE states
 *
 * @author   Jelle De Loecker <jelle@develry.be>
 * @since    0.1.0
 * @version  0.1.0
 */
this.BLE.STATES = {
	ADV         : 0x00000001,
	SCAN        : 0x00000002,
	INIT        : 0x00000004,
	CONN_SL     : 0x00000008,
	ADV_SCAN    : 0x00000010,
	ADV_INIT    : 0x00000020,
	ADV_MA      : 0x00000040,
	ADV_SL      : 0x00000080,
	SCAN_INIT   : 0x00000100,
	SCAN_MA     : 0x00000200,
	SCAN_SL     : 0x00000400,
	INIT_MA     : 0x00000800
};